### ISSUE TITLE
Integration tests failing 

### ISSUE THREAD

**Issue by wlynch** [tektoncd/chains#577]
Sample run: https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_chains/575/pull-tekton-chains-integration-tests/1575147898453102592

<details>
  <summary>Raw</summary>

```
    examples_test.go:94: Got attestation: {"_type":"https://in-toto.io/Statement/v0.1","predicateType":"https://slsa.dev/provenance/v0.2","subject":[{"name":"gcr.io/foo/bar","digest":{"sha256":"05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5"}}],"predicate":{"builder":{"id":"https://tekton.dev/chains/v2"},"buildType":"tekton.dev/v1beta1/TaskRun","invocation":{"configSource":{},"parameters":{}},"buildConfig":{"steps":[{"entryPoint":"","arguments":null,"environment":{"container":"create-dir-builtimage-ksczd","image":"docker-pullable://cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791"},"annotations":null},{"entryPoint":"","arguments":null,"environment":{"container":"git-source-sourcerepo-p74f2","image":"docker-pullable://gcr.io/tekton-nightly/github.com/tektoncd/pipeline/cmd/git-init@sha256:884f27a9280dde5f9559705c32c001d07abca3a9216d4806805661da5d42a9da"},"annotations":null},{"entryPoint":"set -e\ncat \u003c\u003cEOF \u003e $(inputs.resources.sourcerepo.path)/index.json\n{\n\"schemaVersion\": 2,\n\"manifests\": [\n    {\n    \"mediaType\": \"application/vnd.oci.image.index.v1+json\",\n    \"size\": 314,\n    \"digest\": \"sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5\"\n    }\n]\n}\n","arguments":null,"environment":{"container":"build-and-push","image":"docker-pullable://busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5"},"annotations":null},{"entryPoint":"cat $(inputs.resources.sourcerepo.path)/index.json","arguments":null,"environment":{"container":"echo","image":"docker-pullable://busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5"},"annotations":null},{"entryPoint":"/ko-app/imagedigestexporter","arguments":["-images","[{\"name\":\"builtImage\",\"type\":\"image\",\"url\":\"gcr.io/foo/bar\",\"digest\":\"\",\"OutputImageDir\":\"/workspace/sourcerepo\"}]"],"environment":{"container":"image-digest-exporter-7k758","image":"docker-pullable://gcr.io/tekton-nightly/github.com/tektoncd/pipeline/cmd/imagedigestexporter@sha256:1a91b0a4b47c485acb8621b911c399c248edfb4e59f0d9979103752c3799da7a"},"annotations":null}]},"metadata":{"buildStartedOn":"2022-09-28T16:09:26Z","buildFinishedOn":"2022-09-28T16:09:40Z","completeness":{"parameters":false,"environment":false,"materials":false},"reproducible":false},"materials":[{"uri":"git+https://github.com/GoogleContainerTools/skaffold@v0.32.0","digest":{"sha1":"6ed7aad5e8a36052ee5f6079fc91368e362121f7"}}]}}
    examples_test.go:153: Reading expected provenance from testdata/intoto/task-output-image.json
    examples_test.go:196: Expected attestation: {
            "_type": "https://in-toto.io/Statement/v0.1",
            "predicateType": "https://slsa.dev/provenance/v0.2",
            "subject": [
                {
                    "name": "gcr.io/foo/bar",
                    "digest": {
                        "sha256": "05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5"
                    }
                }
            ],
            "predicate": {
                "builder": {
                    "id": "https://tekton.dev/chains/v2"
                },
                "buildType": "tekton.dev/v1beta1/TaskRun",
                "invocation": {
                    "configSource": {},
                    "parameters": {}
                },
                "buildConfig": {
                    "steps": [
                        {
                            "entryPoint": "",
                            "arguments": null,
                            "environment": {
                                "container": "create-dir-builtimage-ksczd",
                                "image": "docker-pullable://cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791"
                            },
                            "annotations": null
                        },
                        {
                            "entryPoint": "",
                            "arguments": null,
                            "environment": {
                                "container": "git-source-sourcerepo-p74f2",
                                "image": "docker-pullable://gcr.io/tekton-nightly/github.com/tektoncd/pipeline/cmd/git-init@sha256:884f27a9280dde5f9559705c32c001d07abca3a9216d4806805661da5d42a9da"
                            },
                            "annotations": null
                        },
                        {
                            "entryPoint": "set -e\ncat \u003c\u003cEOF \u003e $(inputs.resources.sourcerepo.path)/index.json\n{\n\"schemaVersion\": 2,\n\"manifests\": [\n    {\n    \"mediaType\": \"application/vnd.oci.image.index.v1+json\",\n    \"size\": 314,\n    \"digest\": \"sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5\"\n    }\n]\n}\n",
                            "arguments": null,
                            "environment": {
                                "container": "build-and-push",
                                "image": "docker-pullable://busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5"
                            },
                            "annotations": null
                        },
                        {
                            "entryPoint": "cat $(inputs.resources.sourcerepo.path)/index.json",
                            "arguments": null,
                            "environment": {
                                "container": "echo",
                                "image": "docker-pullable://busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5"
                            },
                            "annotations": null
                        },
                        {
                            "entryPoint": "",
                            "arguments": null,
                            "environment": {
                                "container": "image-digest-exporter-7k758",
                                "image": "docker-pullable://gcr.io/tekton-nightly/github.com/tektoncd/pipeline/cmd/imagedigestexporter@sha256:1a91b0a4b47c485acb8621b911c399c248edfb4e59f0d9979103752c3799da7a"
                            },
                            "annotations": null
                        }
                    ]
                },
                "metadata": {
                    "buildStartedOn": "2022-09-28T16:09:26Z",
                    "buildFinishedOn": "2022-09-28T16:09:40Z",
                    "completeness": {
                        "parameters": false,
                        "environment": false,
                        "materials": false
                    },
                    "reproducible": false
                },
                "materials": [
                    {
                        "uri": "git+https://github.com/GoogleContainerTools/skaffold@v0.32.0",
                        "digest": {
                            "sha1": "6ed7aad5e8a36052ee5f6079fc91368e362121f7"
                        }
                    }
                ]
            }
        }
    examples_test.go:104: expected and got do not match:
          in_toto.ProvenanceStatement{
          }}
```
</details>

I have a sneaking suspicion that this is may be related to upstream pipelines changes, since I pinned the pipelines yaml to v0.39.0 in https://github.com/tektoncd/chains/commit/1446cf828c3b07011a62dc0a4859496634b292b4 and it passed: https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_chains/574/pull-tekton-chains-integration-tests/1574872587211640832

Will dig in deeper though.

**Comment by wlynch** [comment]
This is a breaking change to Pipelines happening somewhere [between v0.40.0 and v0.40.1](https://github.com/tektoncd/pipeline/compare/v0.40.0...v0.40.1) with how PipelineResources are being handled - Confirmed this is working in v0.40.0. cc @jeromeju @piyush-garg 

The release of v0.40.1 yesterday roughly lines up to when we started seeing this behavior. Nothing in the release notes suggests that the Pipelines behavior should have changed.

Input yaml: https://github.com/tektoncd/chains/blob/main/examples/taskruns/task-output-image.yaml

<details>
  <summary>v0.40.0</summary>

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  annotations:
    chains.tekton.dev/cert-05f95b26ed10: ""
    chains.tekton.dev/cert-taskrun-7048453f-35a2-40fb-911c-eec88fba0792: ""
    chains.tekton.dev/chain-05f95b26ed10: ""
    chains.tekton.dev/chain-taskrun-7048453f-35a2-40fb-911c-eec88fba0792: ""
    chains.tekton.dev/payload-05f95b26ed10: eyJjcml0aWNhbCI6eyJpZGVudGl0eSI6eyJkb2NrZXItcmVmZXJlbmNlIjoiZ2NyLmlvL2Zvby9iYXIifSwiaW1hZ2UiOnsiZG9ja2VyLW1hbmlmZXN0LWRpZ2VzdCI6InNoYTI1NjowNWY5NWIyNmVkMTA2NjhiNzE4M2MxZTJkYTk4NjEwZTkxMzcyZmE5ZjUxMDA0NmQ0Y2U1ODEyYWRkYWQ4NmI1In0sInR5cGUiOiJjb3NpZ24gY29udGFpbmVyIGltYWdlIHNpZ25hdHVyZSJ9LCJvcHRpb25hbCI6bnVsbH0=
    chains.tekton.dev/payload-taskrun-7048453f-35a2-40fb-911c-eec88fba0792: eyJjb25kaXRpb25zIjpbeyJ0eXBlIjoiU3VjY2VlZGVkIiwic3RhdHVzIjoiVHJ1ZSIsImxhc3RUcmFuc2l0aW9uVGltZSI6IjIwMjItMDktMjhUMTc6NDE6MzJaIiwicmVhc29uIjoiU3VjY2VlZGVkIiwibWVzc2FnZSI6IkFsbCBTdGVwcyBoYXZlIGNvbXBsZXRlZCBleGVjdXRpbmcifV0sInBvZE5hbWUiOiJidWlsZC1wdXNoLXJ1bi1vdXRwdXQtaW1hZ2UtaHBzengtcG9kIiwic3RhcnRUaW1lIjoiMjAyMi0wOS0yOFQxNzo0MToxNloiLCJjb21wbGV0aW9uVGltZSI6IjIwMjItMDktMjhUMTc6NDE6MzJaIiwic3RlcHMiOlt7InRlcm1pbmF0ZWQiOnsiZXhpdENvZGUiOjAsInJlYXNvbiI6IkNvbXBsZXRlZCIsInN0YXJ0ZWRBdCI6IjIwMjItMDktMjhUMTc6NDE6MjhaIiwiZmluaXNoZWRBdCI6IjIwMjItMDktMjhUMTc6NDE6MjhaIiwiY29udGFpbmVySUQiOiJjb250YWluZXJkOi8vMTBjMWY2YTQzYzdlMTIzNDBmODE5NWFjYmZjYzBjMGMwNjZjZThiYjY2MzBlOTJkOGNhNjRhMmY1MWUwYjIxOCJ9LCJuYW1lIjoiY3JlYXRlLWRpci1idWlsdGltYWdlLXI4N2tqIiwiY29udGFpbmVyIjoic3RlcC1jcmVhdGUtZGlyLWJ1aWx0aW1hZ2Utcjg3a2oiLCJpbWFnZUlEIjoiY2dyLmRldi9jaGFpbmd1YXJkL2J1c3lib3hAc2hhMjU2OjE5ZjAyMjc2YmY4ZGJkZDYyZjA2OWI5MjJmMTBjNjUyNjJjYzM0YjcxMGVlYTI2ZmY5MjgxMjlhNzM2YmU3OTEifSx7InRlcm1pbmF0ZWQiOnsiZXhpdENvZGUiOjAsInJlYXNvbiI6IkNvbXBsZXRlZCIsIm1lc3NhZ2UiOiJbe1wia2V5XCI6XCJjb21taXRcIixcInZhbHVlXCI6XCI2ZWQ3YWFkNWU4YTM2MDUyZWU1ZjYwNzlmYzkxMzY4ZTM2MjEyMWY3XCIsXCJyZXNvdXJjZU5hbWVcIjpcInNvdXJjZXJlcG9cIn0se1wia2V5XCI6XCJ1cmxcIixcInZhbHVlXCI6XCJodHRwczovL2dpdGh1Yi5jb20vR29vZ2xlQ29udGFpbmVyVG9vbHMvc2thZmZvbGRcIixcInJlc291cmNlTmFtZVwiOlwic291cmNlcmVwb1wifV0iLCJzdGFydGVkQXQiOiIyMDIyLTA5LTI4VDE3OjQxOjI4WiIsImZpbmlzaGVkQXQiOiIyMDIyLTA5LTI4VDE3OjQxOjMxWiIsImNvbnRhaW5lcklEIjoiY29udGFpbmVyZDovLzVmZmZkZTA0N2YzYmM2MWE1ZWJlYTcxZTVjNTU5ODlhYjkwYjY5ZTUwYzc2MjBmMGZiZTE5N2MyOTRjOTVjZDMifSwibmFtZSI6ImdpdC1zb3VyY2Utc291cmNlcmVwby1zbW5icyIsImNvbnRhaW5lciI6InN0ZXAtZ2l0LXNvdXJjZS1zb3VyY2VyZXBvLXNtbmJzIiwiaW1hZ2VJRCI6Imdjci5pby90ZWt0b24tcmVsZWFzZXMvZ2l0aHViLmNvbS90ZWt0b25jZC9waXBlbGluZS9jbWQvZ2l0LWluaXRAc2hhMjU2OjZlODc1ZjJkNjZlYjRjZjlmYWNlYjA2YjYwZDg0MDE4NWE0ZmM3MWI5YjE2Y2YzMWY5NzdjOWMxYjIxYWJjMjgifSx7InRlcm1pbmF0ZWQiOnsiZXhpdENvZGUiOjAsInJlYXNvbiI6IkNvbXBsZXRlZCIsInN0YXJ0ZWRBdCI6IjIwMjItMDktMjhUMTc6NDE6MzFaIiwiZmluaXNoZWRBdCI6IjIwMjItMDktMjhUMTc6NDE6MzFaIiwiY29udGFpbmVySUQiOiJjb250YWluZXJkOi8vYjAyNTk1ZWQyNTU0NzIyMDA3NGNlN2YwNmQxN2VlOGJmMzhkZmY0NDM1NmQyODk2MDE1NDM4ZDc0NTU4MjlkOCJ9LCJuYW1lIjoiYnVpbGQtYW5kLXB1c2giLCJjb250YWluZXIiOiJzdGVwLWJ1aWxkLWFuZC1wdXNoIiwiaW1hZ2VJRCI6ImRvY2tlci5pby9saWJyYXJ5L2J1c3lib3hAc2hhMjU2OmFkOWJkNTdhM2E1N2NjOTU1MTVjNTM3Yjg5YWFhNjlkODNhNmRmNTRjNDA1MGZjZjJiNDFhZDM2N2JlYzBjZDUifSx7InRlcm1pbmF0ZWQiOnsiZXhpdENvZGUiOjAsInJlYXNvbiI6IkNvbXBsZXRlZCIsInN0YXJ0ZWRBdCI6IjIwMjItMDktMjhUMTc6NDE6MzFaIiwiZmluaXNoZWRBdCI6IjIwMjItMDktMjhUMTc6NDE6MzFaIiwiY29udGFpbmVySUQiOiJjb250YWluZXJkOi8vNzI5ZDk2YzE1MWRjYzQ0MmY3MDU3MTM4Mjk1MmM3MjUxZjNiYTQ3MGM5MjNkZmI1OWQzM2ZjMTA4MmU5Yjg3MCJ9LCJuYW1lIjoiZWNobyIsImNvbnRhaW5lciI6InN0ZXAtZWNobyIsImltYWdlSUQiOiJkb2NrZXIuaW8vbGlicmFyeS9idXN5Ym94QHNoYTI1NjphZDliZDU3YTNhNTdjYzk1NTE1YzUzN2I4OWFhYTY5ZDgzYTZkZjU0YzQwNTBmY2YyYjQxYWQzNjdiZWMwY2Q1In0seyJ0ZXJtaW5hdGVkIjp7ImV4aXRDb2RlIjowLCJyZWFzb24iOiJDb21wbGV0ZWQiLCJtZXNzYWdlIjoiW3tcImtleVwiOlwiZGlnZXN0XCIsXCJ2YWx1ZVwiOlwic2hhMjU2OjA1Zjk1YjI2ZWQxMDY2OGI3MTgzYzFlMmRhOTg2MTBlOTEzNzJmYTlmNTEwMDQ2ZDRjZTU4MTJhZGRhZDg2YjVcIixcInJlc291cmNlTmFtZVwiOlwiYnVpbHRJbWFnZVwifSx7XCJrZXlcIjpcInVybFwiLFwidmFsdWVcIjpcImdjci5pby9mb28vYmFyXCIsXCJyZXNvdXJjZU5hbWVcIjpcImJ1aWx0SW1hZ2VcIn1dIiwic3RhcnRlZEF0IjoiMjAyMi0wOS0yOFQxNzo0MTozMloiLCJmaW5pc2hlZEF0IjoiMjAyMi0wOS0yOFQxNzo0MTozMloiLCJjb250YWluZXJJRCI6ImNvbnRhaW5lcmQ6Ly82ZWEwODYzMmEyODY3NzgxOGNiZjFiZjZmM2I1ODY4NjRlNzNmMWZkZWFiMzZjNzM2NjZmY2EzZTM1MTk5YTU1In0sIm5hbWUiOiJpbWFnZS1kaWdlc3QtZXhwb3J0ZXItdGM0bnAiLCJjb250YWluZXIiOiJzdGVwLWltYWdlLWRpZ2VzdC1leHBvcnRlci10YzRucCIsImltYWdlSUQiOiJnY3IuaW8vdGVrdG9uLXJlbGVhc2VzL2dpdGh1Yi5jb20vdGVrdG9uY2QvcGlwZWxpbmUvY21kL2ltYWdlZGlnZXN0ZXhwb3J0ZXJAc2hhMjU2OjhjYTc3ZWY0NmU5ZWUyYWFiNDJiYWRhZjE1NTNlMDVjZDRhZDJmMjEyNmI0MmVkZTQyMmVmYjYyYmU1ZWM3NjMifV0sInJlc291cmNlc1Jlc3VsdCI6W3sia2V5IjoiY29tbWl0IiwidmFsdWUiOiI2ZWQ3YWFkNWU4YTM2MDUyZWU1ZjYwNzlmYzkxMzY4ZTM2MjEyMWY3IiwicmVzb3VyY2VOYW1lIjoic291cmNlcmVwbyJ9LHsia2V5IjoidXJsIiwidmFsdWUiOiJodHRwczovL2dpdGh1Yi5jb20vR29vZ2xlQ29udGFpbmVyVG9vbHMvc2thZmZvbGQiLCJyZXNvdXJjZU5hbWUiOiJzb3VyY2VyZXBvIn0seyJrZXkiOiJkaWdlc3QiLCJ2YWx1ZSI6InNoYTI1NjowNWY5NWIyNmVkMTA2NjhiNzE4M2MxZTJkYTk4NjEwZTkxMzcyZmE5ZjUxMDA0NmQ0Y2U1ODEyYWRkYWQ4NmI1IiwicmVzb3VyY2VOYW1lIjoiYnVpbHRJbWFnZSJ9LHsia2V5IjoidXJsIiwidmFsdWUiOiJnY3IuaW8vZm9vL2JhciIsInJlc291cmNlTmFtZSI6ImJ1aWx0SW1hZ2UifV0sInRhc2tTcGVjIjp7InJlc291cmNlcyI6eyJpbnB1dHMiOlt7Im5hbWUiOiJzb3VyY2VyZXBvIiwidHlwZSI6ImdpdCJ9XSwib3V0cHV0cyI6W3sibmFtZSI6ImJ1aWx0SW1hZ2UiLCJ0eXBlIjoiaW1hZ2UiLCJ0YXJnZXRQYXRoIjoiL3dvcmtzcGFjZS9zb3VyY2VyZXBvIn1dfSwic3RlcHMiOlt7Im5hbWUiOiJidWlsZC1hbmQtcHVzaCIsImltYWdlIjoiYnVzeWJveCIsInJlc291cmNlcyI6e30sInNjcmlwdCI6InNldCAtZVxuY2F0IFx1MDAzY1x1MDAzY0VPRiBcdTAwM2UgJChpbnB1dHMucmVzb3VyY2VzLnNvdXJjZXJlcG8ucGF0aCkvaW5kZXguanNvblxue1xuXCJzY2hlbWFWZXJzaW9uXCI6IDIsXG5cIm1hbmlmZXN0c1wiOiBbXG4gICAge1xuICAgIFwibWVkaWFUeXBlXCI6IFwiYXBwbGljYXRpb24vdm5kLm9jaS5pbWFnZS5pbmRleC52MStqc29uXCIsXG4gICAgXCJzaXplXCI6IDMxNCxcbiAgICBcImRpZ2VzdFwiOiBcInNoYTI1NjowNWY5NWIyNmVkMTA2NjhiNzE4M2MxZTJkYTk4NjEwZTkxMzcyZmE5ZjUxMDA0NmQ0Y2U1ODEyYWRkYWQ4NmI1XCJcbiAgICB9XG5dXG59XG4ifSx7Im5hbWUiOiJlY2hvIiwiaW1hZ2UiOiJidXN5Ym94IiwicmVzb3VyY2VzIjp7fSwic2NyaXB0IjoiY2F0ICQoaW5wdXRzLnJlc291cmNlcy5zb3VyY2VyZXBvLnBhdGgpL2luZGV4Lmpzb24ifSx7Im5hbWUiOiJpbWFnZS1kaWdlc3QtZXhwb3J0ZXItdGM0bnAiLCJpbWFnZSI6Imdjci5pby90ZWt0b24tcmVsZWFzZXMvZ2l0aHViLmNvbS90ZWt0b25jZC9waXBlbGluZS9jbWQvaW1hZ2VkaWdlc3RleHBvcnRlcjp2MC40MC4xQHNoYTI1Njo4Y2E3N2VmNDZlOWVlMmFhYjQyYmFkYWYxNTUzZTA1Y2Q0YWQyZjIxMjZiNDJlZGU0MjJlZmI2MmJlNWVjNzYzIiwiY29tbWFuZCI6WyIva28tYXBwL2ltYWdlZGlnZXN0ZXhwb3J0ZXIiXSwiYXJncyI6WyItaW1hZ2VzIiwiW3tcIm5hbWVcIjpcImJ1aWx0SW1hZ2VcIixcInR5cGVcIjpcImltYWdlXCIsXCJ1cmxcIjpcImdjci5pby9mb28vYmFyXCIsXCJkaWdlc3RcIjpcIlwiLFwiT3V0cHV0SW1hZ2VEaXJcIjpcIi93b3Jrc3BhY2Uvc291cmNlcmVwb1wifV0iXSwicmVzb3VyY2VzIjp7fX1dfX0=
    chains.tekton.dev/retries: "0"
    chains.tekton.dev/signature-05f95b26ed10: MEQCIDgAkeWuPyG2reIP+rfkYfuebdcP6kymMNAk1G5SrdX1AiALUm6Ku6LB1+u2OIYSk2odEV9CoFUVpTwedOm33Eb9LQ==
    chains.tekton.dev/signature-taskrun-7048453f-35a2-40fb-911c-eec88fba0792: MEUCIEDCJe2Fmbu/9WkP4GoqQIk29IFQ9IHkTUKR8eL+14xqAiEA6w4ncckb68K0t3GDFGcGNzsHOJDg6HhZfaLeLqpuJFE=
    chains.tekton.dev/signed: "true"
    pipeline.tekton.dev/release: 9221ac3-dirty
  creationTimestamp: "2022-09-28T17:41:16Z"
  finalizers:
  - chains.tekton.dev
  generateName: build-push-run-output-image-
  generation: 1
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
  name: build-push-run-output-image-hpszx
  namespace: default
  resourceVersion: "171161"
  uid: 7048453f-35a2-40fb-911c-eec88fba0792
spec:
  resources:
    inputs:
    - name: sourcerepo
      resourceSpec:
        params:
        - name: revision
          value: v0.32.0
        - name: url
          value: https://github.com/GoogleContainerTools/skaffold
        type: git
    outputs:
    - name: builtImage
      resourceSpec:
        params:
        - name: url
          value: gcr.io/foo/bar
        type: image
  serviceAccountName: default
  taskSpec:
    resources:
      inputs:
      - name: sourcerepo
        type: git
      outputs:
      - name: builtImage
        targetPath: /workspace/sourcerepo
        type: image
    steps:
    - image: busybox
      name: build-and-push
      resources: {}
      script: |
        set -e
        cat <<EOF > $(inputs.resources.sourcerepo.path)/index.json
        {
        "schemaVersion": 2,
        "manifests": [
            {
            "mediaType": "application/vnd.oci.image.index.v1+json",
            "size": 314,
            "digest": "sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5"
            }
        ]
        }
    - image: busybox
      name: echo
      resources: {}
      script: cat $(inputs.resources.sourcerepo.path)/index.json
  timeout: 1h0m0s
status:
  completionTime: "2022-09-28T17:41:32Z"
  conditions:
  - lastTransitionTime: "2022-09-28T17:41:32Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: build-push-run-output-image-hpszx-pod
  resourcesResult:
  - key: commit
    resourceName: sourcerepo
    value: 6ed7aad5e8a36052ee5f6079fc91368e362121f7
  - key: url
    resourceName: sourcerepo
    value: https://github.com/GoogleContainerTools/skaffold
  - key: digest
    resourceName: builtImage
    value: sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5
  - key: url
    resourceName: builtImage
    value: gcr.io/foo/bar
  startTime: "2022-09-28T17:41:16Z"
  steps:
  - container: step-create-dir-builtimage-r87kj
    imageID: cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
    name: create-dir-builtimage-r87kj
    terminated:
      containerID: containerd://10c1f6a43c7e12340f8195acbfcc0c0c066ce8bb6630e92d8ca64a2f51e0b218
      exitCode: 0
      finishedAt: "2022-09-28T17:41:28Z"
      reason: Completed
      startedAt: "2022-09-28T17:41:28Z"
  - container: step-git-source-sourcerepo-smnbs
    imageID: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:6e875f2d66eb4cf9faceb06b60d840185a4fc71b9b16cf31f977c9c1b21abc28
    name: git-source-sourcerepo-smnbs
    terminated:
      containerID: containerd://5fffde047f3bc61a5ebea71e5c55989ab90b69e50c7620f0fbe197c294c95cd3
      exitCode: 0
      finishedAt: "2022-09-28T17:41:31Z"
      message: '[{"key":"commit","value":"6ed7aad5e8a36052ee5f6079fc91368e362121f7","resourceName":"sourcerepo"},{"key":"url","value":"https://github.com/GoogleContainerTools/skaffold","resourceName":"sourcerepo"}]'
      reason: Completed
      startedAt: "2022-09-28T17:41:28Z"
  - container: step-build-and-push
    imageID: docker.io/library/busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5
    name: build-and-push
    terminated:
      containerID: containerd://b02595ed25547220074ce7f06d17ee8bf38dff44356d2896015438d7455829d8
      exitCode: 0
      finishedAt: "2022-09-28T17:41:31Z"
      reason: Completed
      startedAt: "2022-09-28T17:41:31Z"
  - container: step-echo
    imageID: docker.io/library/busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5
    name: echo
    terminated:
      containerID: containerd://729d96c151dcc442f70571382952c7251f3ba470c923dfb59d33fc1082e9b870
      exitCode: 0
      finishedAt: "2022-09-28T17:41:31Z"
      reason: Completed
      startedAt: "2022-09-28T17:41:31Z"
  - container: step-image-digest-exporter-tc4np
    imageID: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter@sha256:8ca77ef46e9ee2aab42badaf1553e05cd4ad2f2126b42ede422efb62be5ec763
    name: image-digest-exporter-tc4np
    terminated:
      containerID: containerd://6ea08632a28677818cbf1bf6f3b586864e73f1fdeab36c73666fca3e35199a55
      exitCode: 0
      finishedAt: "2022-09-28T17:41:32Z"
      message: '[{"key":"digest","value":"sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5","resourceName":"builtImage"},{"key":"url","value":"gcr.io/foo/bar","resourceName":"builtImage"}]'
      reason: Completed
      startedAt: "2022-09-28T17:41:32Z"
  taskSpec:
    resources:
      inputs:
      - name: sourcerepo
        type: git
      outputs:
      - name: builtImage
        targetPath: /workspace/sourcerepo
        type: image
    steps:
    - image: busybox
      name: build-and-push
      resources: {}
      script: |
        set -e
        cat <<EOF > $(inputs.resources.sourcerepo.path)/index.json
        {
        "schemaVersion": 2,
        "manifests": [
            {
            "mediaType": "application/vnd.oci.image.index.v1+json",
            "size": 314,
            "digest": "sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5"
            }
        ]
        }
    - image: busybox
      name: echo
      resources: {}
      script: cat $(inputs.resources.sourcerepo.path)/index.json
    - args:
      - -images
      - '[{"name":"builtImage","type":"image","url":"gcr.io/foo/bar","digest":"","OutputImageDir":"/workspace/sourcerepo"}]'
      command:
      - /ko-app/imagedigestexporter
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.40.1@sha256:8ca77ef46e9ee2aab42badaf1553e05cd4ad2f2126b42ede422efb62be5ec763
      name: image-digest-exporter-tc4np
      resources: {}
```

</details>

<details>
  <summary>v0.40.1</summary>

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  annotations:
    chains.tekton.dev/cert-05f95b26ed10: ""
    chains.tekton.dev/cert-taskrun-410cdf01-b671-4160-8946-84f4bf751f25: ""
    chains.tekton.dev/chain-05f95b26ed10: ""
    chains.tekton.dev/chain-taskrun-410cdf01-b671-4160-8946-84f4bf751f25: ""
    chains.tekton.dev/payload-05f95b26ed10: eyJjcml0aWNhbCI6eyJpZGVudGl0eSI6eyJkb2NrZXItcmVmZXJlbmNlIjoiZ2NyLmlvL2Zvby9iYXIifSwiaW1hZ2UiOnsiZG9ja2VyLW1hbmlmZXN0LWRpZ2VzdCI6InNoYTI1NjowNWY5NWIyNmVkMTA2NjhiNzE4M2MxZTJkYTk4NjEwZTkxMzcyZmE5ZjUxMDA0NmQ0Y2U1ODEyYWRkYWQ4NmI1In0sInR5cGUiOiJjb3NpZ24gY29udGFpbmVyIGltYWdlIHNpZ25hdHVyZSJ9LCJvcHRpb25hbCI6bnVsbH0=
    chains.tekton.dev/payload-taskrun-410cdf01-b671-4160-8946-84f4bf751f25: eyJjb25kaXRpb25zIjpbeyJ0eXBlIjoiU3VjY2VlZGVkIiwic3RhdHVzIjoiVHJ1ZSIsImxhc3RUcmFuc2l0aW9uVGltZSI6IjIwMjItMDktMjhUMTc6MzQ6NDhaIiwicmVhc29uIjoiU3VjY2VlZGVkIiwibWVzc2FnZSI6IkFsbCBTdGVwcyBoYXZlIGNvbXBsZXRlZCBleGVjdXRpbmcifV0sInBvZE5hbWUiOiJidWlsZC1wdXNoLXJ1bi1vdXRwdXQtaW1hZ2UtcWM2a2wtcG9kIiwic3RhcnRUaW1lIjoiMjAyMi0wOS0yOFQxNzozNDozNVoiLCJjb21wbGV0aW9uVGltZSI6IjIwMjItMDktMjhUMTc6MzQ6NDhaIiwic3RlcHMiOlt7InRlcm1pbmF0ZWQiOnsiZXhpdENvZGUiOjAsInJlYXNvbiI6IkNvbXBsZXRlZCIsInN0YXJ0ZWRBdCI6IjIwMjItMDktMjhUMTc6MzQ6NDRaIiwiZmluaXNoZWRBdCI6IjIwMjItMDktMjhUMTc6MzQ6NDRaIiwiY29udGFpbmVySUQiOiJjb250YWluZXJkOi8vOTQ2Y2UzYmI1ZjYyYTNlMjY4YmQwODQ2OWE1NWUwYzIyMjk4YTU1ZTdkNjUxNmI4M2U4YjhlNTU2MTQwYzRiZiJ9LCJuYW1lIjoiY3JlYXRlLWRpci1idWlsdGltYWdlLTk4OHE4IiwiY29udGFpbmVyIjoic3RlcC1jcmVhdGUtZGlyLWJ1aWx0aW1hZ2UtOTg4cTgiLCJpbWFnZUlEIjoiY2dyLmRldi9jaGFpbmd1YXJkL2J1c3lib3hAc2hhMjU2OjE5ZjAyMjc2YmY4ZGJkZDYyZjA2OWI5MjJmMTBjNjUyNjJjYzM0YjcxMGVlYTI2ZmY5MjgxMjlhNzM2YmU3OTEifSx7InRlcm1pbmF0ZWQiOnsiZXhpdENvZGUiOjAsInJlYXNvbiI6IkNvbXBsZXRlZCIsIm1lc3NhZ2UiOiJbe1wia2V5XCI6XCJjb21taXRcIixcInZhbHVlXCI6XCI2ZWQ3YWFkNWU4YTM2MDUyZWU1ZjYwNzlmYzkxMzY4ZTM2MjEyMWY3XCIsXCJyZXNvdXJjZU5hbWVcIjpcInNvdXJjZXJlcG9cIn0se1wia2V5XCI6XCJ1cmxcIixcInZhbHVlXCI6XCJodHRwczovL2dpdGh1Yi5jb20vR29vZ2xlQ29udGFpbmVyVG9vbHMvc2thZmZvbGRcIixcInJlc291cmNlTmFtZVwiOlwic291cmNlcmVwb1wifV0iLCJzdGFydGVkQXQiOiIyMDIyLTA5LTI4VDE3OjM0OjQ0WiIsImZpbmlzaGVkQXQiOiIyMDIyLTA5LTI4VDE3OjM0OjQ2WiIsImNvbnRhaW5lcklEIjoiY29udGFpbmVyZDovL2E5MzYyYzcxNWNiNzRiNGUxNjc0ZjBlYjQxM2FmYmQ2ZjFiZTkzNmUyNDgxYjBmYzdhNmMzZGZjMzFmNjk2MmYifSwibmFtZSI6ImdpdC1zb3VyY2Utc291cmNlcmVwby1waGJzcyIsImNvbnRhaW5lciI6InN0ZXAtZ2l0LXNvdXJjZS1zb3VyY2VyZXBvLXBoYnNzIiwiaW1hZ2VJRCI6Imdjci5pby90ZWt0b24tcmVsZWFzZXMvZ2l0aHViLmNvbS90ZWt0b25jZC9waXBlbGluZS9jbWQvZ2l0LWluaXRAc2hhMjU2OjNhMWQzZTU3NjkyZTk2NjYzYzc2ZTQ5MDllZjVlZjU1NWE5MzZlYjU5OWJjNDYxNzUyMjFhYjRjOTRlNGVjNTIifSx7InRlcm1pbmF0ZWQiOnsiZXhpdENvZGUiOjAsInJlYXNvbiI6IkNvbXBsZXRlZCIsInN0YXJ0ZWRBdCI6IjIwMjItMDktMjhUMTc6MzQ6NDdaIiwiZmluaXNoZWRBdCI6IjIwMjItMDktMjhUMTc6MzQ6NDdaIiwiY29udGFpbmVySUQiOiJjb250YWluZXJkOi8vZTU5MDk5ZmFhOGZkODE1ZjM3ZDQ3YWJhNjY5ZTIyNTgwNGUzODA2MjlmYjI3ZDEzNDA0ZGUxOTdhNzZiOTg5NCJ9LCJuYW1lIjoiYnVpbGQtYW5kLXB1c2giLCJjb250YWluZXIiOiJzdGVwLWJ1aWxkLWFuZC1wdXNoIiwiaW1hZ2VJRCI6ImRvY2tlci5pby9saWJyYXJ5L2J1c3lib3hAc2hhMjU2OmFkOWJkNTdhM2E1N2NjOTU1MTVjNTM3Yjg5YWFhNjlkODNhNmRmNTRjNDA1MGZjZjJiNDFhZDM2N2JlYzBjZDUifSx7InRlcm1pbmF0ZWQiOnsiZXhpdENvZGUiOjAsInJlYXNvbiI6IkNvbXBsZXRlZCIsInN0YXJ0ZWRBdCI6IjIwMjItMDktMjhUMTc6MzQ6NDdaIiwiZmluaXNoZWRBdCI6IjIwMjItMDktMjhUMTc6MzQ6NDdaIiwiY29udGFpbmVySUQiOiJjb250YWluZXJkOi8vODZmMTI5NTRiNjA3NTNkYjJhMjA1YWEzODUzNTUzM2MzZmU1YjgxNTk2NGM4NTcxMGFiMDMzMzc1OWJjNGYwMCJ9LCJuYW1lIjoiZWNobyIsImNvbnRhaW5lciI6InN0ZXAtZWNobyIsImltYWdlSUQiOiJkb2NrZXIuaW8vbGlicmFyeS9idXN5Ym94QHNoYTI1NjphZDliZDU3YTNhNTdjYzk1NTE1YzUzN2I4OWFhYTY5ZDgzYTZkZjU0YzQwNTBmY2YyYjQxYWQzNjdiZWMwY2Q1In0seyJ0ZXJtaW5hdGVkIjp7ImV4aXRDb2RlIjowLCJyZWFzb24iOiJDb21wbGV0ZWQiLCJtZXNzYWdlIjoiW3tcImtleVwiOlwiZGlnZXN0XCIsXCJ2YWx1ZVwiOlwic2hhMjU2OjA1Zjk1YjI2ZWQxMDY2OGI3MTgzYzFlMmRhOTg2MTBlOTEzNzJmYTlmNTEwMDQ2ZDRjZTU4MTJhZGRhZDg2YjVcIixcInJlc291cmNlTmFtZVwiOlwiYnVpbHRJbWFnZVwifSx7XCJrZXlcIjpcInVybFwiLFwidmFsdWVcIjpcImdjci5pby9mb28vYmFyXCIsXCJyZXNvdXJjZU5hbWVcIjpcImJ1aWx0SW1hZ2VcIn1dIiwic3RhcnRlZEF0IjoiMjAyMi0wOS0yOFQxNzozNDo0OFoiLCJmaW5pc2hlZEF0IjoiMjAyMi0wOS0yOFQxNzozNDo0OFoiLCJjb250YWluZXJJRCI6ImNvbnRhaW5lcmQ6Ly8wZWYwYTBmMGExOGJlMDVhN2E0YzQ4ZjcxZGIxZmVjNjVkOTUyMmIwYmQ1OGYxMjdkNjIzMTZmOTJlZWY0MTVhIn0sIm5hbWUiOiJpbWFnZS1kaWdlc3QtZXhwb3J0ZXItNnd3NHIiLCJjb250YWluZXIiOiJzdGVwLWltYWdlLWRpZ2VzdC1leHBvcnRlci02d3c0ciIsImltYWdlSUQiOiJnY3IuaW8vdGVrdG9uLXJlbGVhc2VzL2dpdGh1Yi5jb20vdGVrdG9uY2QvcGlwZWxpbmUvY21kL2ltYWdlZGlnZXN0ZXhwb3J0ZXJAc2hhMjU2OjY1YzcwOGI0MTFjMDg0OWI5ZDAwOWRjMmIzNDJmMTRhZmYyZDRmNTk3N2QyMjNhY2RiYmNjZWQ3N2RlMTU4NDUifV0sInJlc291cmNlc1Jlc3VsdCI6W3sia2V5IjoiY29tbWl0IiwidmFsdWUiOiI2ZWQ3YWFkNWU4YTM2MDUyZWU1ZjYwNzlmYzkxMzY4ZTM2MjEyMWY3IiwicmVzb3VyY2VOYW1lIjoic291cmNlcmVwbyJ9LHsia2V5IjoidXJsIiwidmFsdWUiOiJodHRwczovL2dpdGh1Yi5jb20vR29vZ2xlQ29udGFpbmVyVG9vbHMvc2thZmZvbGQiLCJyZXNvdXJjZU5hbWUiOiJzb3VyY2VyZXBvIn0seyJrZXkiOiJkaWdlc3QiLCJ2YWx1ZSI6InNoYTI1NjowNWY5NWIyNmVkMTA2NjhiNzE4M2MxZTJkYTk4NjEwZTkxMzcyZmE5ZjUxMDA0NmQ0Y2U1ODEyYWRkYWQ4NmI1IiwicmVzb3VyY2VOYW1lIjoiYnVpbHRJbWFnZSJ9LHsia2V5IjoidXJsIiwidmFsdWUiOiJnY3IuaW8vZm9vL2JhciIsInJlc291cmNlTmFtZSI6ImJ1aWx0SW1hZ2UifV0sInRhc2tTcGVjIjp7InJlc291cmNlcyI6eyJpbnB1dHMiOlt7Im5hbWUiOiJzb3VyY2VyZXBvIiwidHlwZSI6ImdpdCJ9XSwib3V0cHV0cyI6W3sibmFtZSI6ImJ1aWx0SW1hZ2UiLCJ0eXBlIjoiaW1hZ2UiLCJ0YXJnZXRQYXRoIjoiL3dvcmtzcGFjZS9zb3VyY2VyZXBvIn1dfSwic3RlcHMiOlt7Im5hbWUiOiJidWlsZC1hbmQtcHVzaCIsImltYWdlIjoiYnVzeWJveCIsInJlc291cmNlcyI6e30sInNjcmlwdCI6InNldCAtZVxuY2F0IFx1MDAzY1x1MDAzY0VPRiBcdTAwM2UgJChpbnB1dHMucmVzb3VyY2VzLnNvdXJjZXJlcG8ucGF0aCkvaW5kZXguanNvblxue1xuXCJzY2hlbWFWZXJzaW9uXCI6IDIsXG5cIm1hbmlmZXN0c1wiOiBbXG4gICAge1xuICAgIFwibWVkaWFUeXBlXCI6IFwiYXBwbGljYXRpb24vdm5kLm9jaS5pbWFnZS5pbmRleC52MStqc29uXCIsXG4gICAgXCJzaXplXCI6IDMxNCxcbiAgICBcImRpZ2VzdFwiOiBcInNoYTI1NjowNWY5NWIyNmVkMTA2NjhiNzE4M2MxZTJkYTk4NjEwZTkxMzcyZmE5ZjUxMDA0NmQ0Y2U1ODEyYWRkYWQ4NmI1XCJcbiAgICB9XG5dXG59XG4ifSx7Im5hbWUiOiJlY2hvIiwiaW1hZ2UiOiJidXN5Ym94IiwicmVzb3VyY2VzIjp7fSwic2NyaXB0IjoiY2F0ICQoaW5wdXRzLnJlc291cmNlcy5zb3VyY2VyZXBvLnBhdGgpL2luZGV4Lmpzb24ifV19fQ==
    chains.tekton.dev/retries: "0"
    chains.tekton.dev/signature-05f95b26ed10: MEQCIEHedg49SGTke9wUs93CWyIgAE7z2CiRKvft+9NFvu01AiBDq4I02wMPbkF3A4HnmchkVThTyWnyHPNLL2dqL8Pyjw==
    chains.tekton.dev/signature-taskrun-410cdf01-b671-4160-8946-84f4bf751f25: MEUCIQDpDkjAwCxi2IJGo/ceBj1KWseDts2ahyaW6W5nQ0YxzwIgU7gW3al8EFnIFXm4cFpNYyF2EQvSXRcyVKXscRw8og8=
    chains.tekton.dev/signed: "true"
    pipeline.tekton.dev/release: 9221ac3-dirty
  creationTimestamp: "2022-09-28T17:34:35Z"
  finalizers:
  - chains.tekton.dev
  generateName: build-push-run-output-image-
  generation: 1
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
  name: build-push-run-output-image-qc6kl
  namespace: default
  resourceVersion: "171159"
  uid: 410cdf01-b671-4160-8946-84f4bf751f25
spec:
  resources:
    inputs:
    - name: sourcerepo
      resourceSpec:
        params:
        - name: revision
          value: v0.32.0
        - name: url
          value: https://github.com/GoogleContainerTools/skaffold
        type: git
    outputs:
    - name: builtImage
      resourceSpec:
        params:
        - name: url
          value: gcr.io/foo/bar
        type: image
  serviceAccountName: default
  taskSpec:
    resources:
      inputs:
      - name: sourcerepo
        type: git
      outputs:
      - name: builtImage
        targetPath: /workspace/sourcerepo
        type: image
    steps:
    - image: busybox
      name: build-and-push
      resources: {}
      script: |
        set -e
        cat <<EOF > $(inputs.resources.sourcerepo.path)/index.json
        {
        "schemaVersion": 2,
        "manifests": [
            {
            "mediaType": "application/vnd.oci.image.index.v1+json",
            "size": 314,
            "digest": "sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5"
            }
        ]
        }
    - image: busybox
      name: echo
      resources: {}
      script: cat $(inputs.resources.sourcerepo.path)/index.json
  timeout: 1h0m0s
status:
  completionTime: "2022-09-28T17:34:48Z"
  conditions:
  - lastTransitionTime: "2022-09-28T17:34:48Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: build-push-run-output-image-qc6kl-pod
  resourcesResult:
  - key: commit
    resourceName: sourcerepo
    value: 6ed7aad5e8a36052ee5f6079fc91368e362121f7
  - key: url
    resourceName: sourcerepo
    value: https://github.com/GoogleContainerTools/skaffold
  - key: digest
    resourceName: builtImage
    value: sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5
  - key: url
    resourceName: builtImage
    value: gcr.io/foo/bar
  startTime: "2022-09-28T17:34:35Z"
  steps:
  - container: step-create-dir-builtimage-988q8
    imageID: cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
    name: create-dir-builtimage-988q8
    terminated:
      containerID: containerd://946ce3bb5f62a3e268bd08469a55e0c22298a55e7d6516b83e8b8e556140c4bf
      exitCode: 0
      finishedAt: "2022-09-28T17:34:44Z"
      reason: Completed
      startedAt: "2022-09-28T17:34:44Z"
  - container: step-git-source-sourcerepo-phbss
    imageID: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:3a1d3e57692e96663c76e4909ef5ef555a936eb599bc46175221ab4c94e4ec52
    name: git-source-sourcerepo-phbss
    terminated:
      containerID: containerd://a9362c715cb74b4e1674f0eb413afbd6f1be936e2481b0fc7a6c3dfc31f6962f
      exitCode: 0
      finishedAt: "2022-09-28T17:34:46Z"
      message: '[{"key":"commit","value":"6ed7aad5e8a36052ee5f6079fc91368e362121f7","resourceName":"sourcerepo"},{"key":"url","value":"https://github.com/GoogleContainerTools/skaffold","resourceName":"sourcerepo"}]'
      reason: Completed
      startedAt: "2022-09-28T17:34:44Z"
  - container: step-build-and-push
    imageID: docker.io/library/busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5
    name: build-and-push
    terminated:
      containerID: containerd://e59099faa8fd815f37d47aba669e225804e380629fb27d13404de197a76b9894
      exitCode: 0
      finishedAt: "2022-09-28T17:34:47Z"
      reason: Completed
      startedAt: "2022-09-28T17:34:47Z"
  - container: step-echo
    imageID: docker.io/library/busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5
    name: echo
    terminated:
      containerID: containerd://86f12954b60753db2a205aa38535533c3fe5b815964c85710ab0333759bc4f00
      exitCode: 0
      finishedAt: "2022-09-28T17:34:47Z"
      reason: Completed
      startedAt: "2022-09-28T17:34:47Z"
  - container: step-image-digest-exporter-6ww4r
    imageID: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter@sha256:65c708b411c0849b9d009dc2b342f14aff2d4f5977d223acdbbcced77de15845
    name: image-digest-exporter-6ww4r
    terminated:
      containerID: containerd://0ef0a0f0a18be05a7a4c48f71db1fec65d9522b0bd58f127d62316f92eef415a
      exitCode: 0
      finishedAt: "2022-09-28T17:34:48Z"
      message: '[{"key":"digest","value":"sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5","resourceName":"builtImage"},{"key":"url","value":"gcr.io/foo/bar","resourceName":"builtImage"}]'
      reason: Completed
      startedAt: "2022-09-28T17:34:48Z"
  taskSpec:
    resources:
      inputs:
      - name: sourcerepo
        type: git
      outputs:
      - name: builtImage
        targetPath: /workspace/sourcerepo
        type: image
    steps:
    - image: busybox
      name: build-and-push
      resources: {}
      script: |
        set -e
        cat <<EOF > $(inputs.resources.sourcerepo.path)/index.json
        {
        "schemaVersion": 2,
        "manifests": [
            {
            "mediaType": "application/vnd.oci.image.index.v1+json",
            "size": 314,
            "digest": "sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5"
            }
        ]
        }
    - image: busybox
      name: echo
      resources: {}
      script: cat $(inputs.resources.sourcerepo.path)/index.json
```

</details>

Diff: 

```diff
-    - args:
-      - -images
-      - '[{"name":"builtImage","type":"image","url":"gcr.io/foo/bar","digest":"","OutputImageDir":"/workspace/sourcerepo"}]'
-      command:
-      - /ko-app/imagedigestexporter
-      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.40.1@sha256:8ca77ef46e9ee2aab42badaf1553e05cd4ad2f2126b42ede422efb62be5ec763
-      name: image-digest-exporter-tc4np
-      resources: {}

**Comment by abayer** [comment]
Pretty sure it's https://github.com/tektoncd/pipeline/commit/9cf7590959acd9ad9518e62d56f5941885614446 - that's the code I'm looking at for a flake in Pipeline (https://github.com/tektoncd/pipeline/issues/5574)

**Comment by JeromeJu** [comment]
> with how PipelineResources are being handled
The `resources` field is handled in the way of being serialized into the annotations when converted to v1, which is not being served yet. I think we can safely assume it's not related to the v1 release.

**Comment by abayer** [comment]
https://github.com/tektoncd/pipeline/pull/5576 should fix this!

**Comment by lcarva** [comment]
I see that the fix is in main and 0.40.2, but the integration tests are still failing.

The integration tests use the nightly build which as of today is `v20221004-5d34b0c783`. The commit 5d34b0c783 does include the fix.
